name: InventoryShare
version: '${version}'
main: com.sugar_tree.inventoryshare.InventoryShare
website: https://github.com/the-sugar-tree/InventoryShare
api-version: 1.17
author: sugar_tree
softdepend: [ProtocolLib]
commands:
  inventoryshare:
    usage: /inventoryshare <inventory|advancement|AnnounceDeath|teaminventory|reload> [true|false]
    description: 콘피그 설정
    aliases: [is]