name: InventoryShare
version: '${version}'
description: A plugin for sharing inventory
main: com.sugar_tree.inventoryshare.InventoryShare
website: https://github.com/the-sugar-tree/InventoryShare
api-version: 1.13
author: sugar_tree
softdepend: [ProtocolLib]
commands:
  inventoryshare:
    usage: /inventoryshare <inventory|advancement|AnnounceDeath|teaminventory|reload> [true|false]
    description: Config Management
    aliases: [is]